// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: albums.proto

package albums

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InventoryClient is the client API for Inventory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryClient interface {
	GetAlbumList(ctx context.Context, in *GetAlbumListRequest, opts ...grpc.CallOption) (*GetAlbumListResponse, error)
	GetAlbumById(ctx context.Context, in *GetAlbumByIdRequest, opts ...grpc.CallOption) (*GetAlbumByIdResponse, error)
}

type inventoryClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryClient(cc grpc.ClientConnInterface) InventoryClient {
	return &inventoryClient{cc}
}

func (c *inventoryClient) GetAlbumList(ctx context.Context, in *GetAlbumListRequest, opts ...grpc.CallOption) (*GetAlbumListResponse, error) {
	out := new(GetAlbumListResponse)
	err := c.cc.Invoke(ctx, "/Inventory/GetAlbumList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) GetAlbumById(ctx context.Context, in *GetAlbumByIdRequest, opts ...grpc.CallOption) (*GetAlbumByIdResponse, error) {
	out := new(GetAlbumByIdResponse)
	err := c.cc.Invoke(ctx, "/Inventory/GetAlbumById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServer is the server API for Inventory service.
// All implementations must embed UnimplementedInventoryServer
// for forward compatibility
type InventoryServer interface {
	GetAlbumList(context.Context, *GetAlbumListRequest) (*GetAlbumListResponse, error)
	GetAlbumById(context.Context, *GetAlbumByIdRequest) (*GetAlbumByIdResponse, error)
	mustEmbedUnimplementedInventoryServer()
}

// UnimplementedInventoryServer must be embedded to have forward compatible implementations.
type UnimplementedInventoryServer struct {
}

func (UnimplementedInventoryServer) GetAlbumList(context.Context, *GetAlbumListRequest) (*GetAlbumListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlbumList not implemented")
}
func (UnimplementedInventoryServer) GetAlbumById(context.Context, *GetAlbumByIdRequest) (*GetAlbumByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlbumById not implemented")
}
func (UnimplementedInventoryServer) mustEmbedUnimplementedInventoryServer() {}

// UnsafeInventoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServer will
// result in compilation errors.
type UnsafeInventoryServer interface {
	mustEmbedUnimplementedInventoryServer()
}

func RegisterInventoryServer(s grpc.ServiceRegistrar, srv InventoryServer) {
	s.RegisterService(&Inventory_ServiceDesc, srv)
}

func _Inventory_GetAlbumList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).GetAlbumList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inventory/GetAlbumList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).GetAlbumList(ctx, req.(*GetAlbumListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_GetAlbumById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlbumByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).GetAlbumById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inventory/GetAlbumById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).GetAlbumById(ctx, req.(*GetAlbumByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Inventory_ServiceDesc is the grpc.ServiceDesc for Inventory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inventory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Inventory",
	HandlerType: (*InventoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAlbumList",
			Handler:    _Inventory_GetAlbumList_Handler,
		},
		{
			MethodName: "GetAlbumById",
			Handler:    _Inventory_GetAlbumById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "albums.proto",
}
